# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0026_auto_20150618_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
