# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0027_transactions_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='total',
        ),
    ]
